### ISSUE TITLE
UnionLib incompatible with PneumaticCraft 8.1.3 (1.21.1 NeoForge)

### ISSUE THREAD

**Issue by BIoxyest** [Stereowalker/Reforged#107]
The game just crashes when booting up.
crash logs are different depending on the unionlib version

with UnionLib 12.0.6: [crash log](https://pastebin.com/iQv2mAbp)
with UnionLib 12.0.7 [crash log](https://pastebin.com/ajYR4RB1)

**Comment by Stereowalker** [comment]
This is a tough one. It won't be fixed until I finish the config system I'm working on. That should make this bug go away. Sorry for the trouble
