### ISSUE TITLE
Please update reforged!!

### ISSUE THREAD

**Issue by bvbbbles** [Stereowalker/Reforged#108]
Every time I try to play with my 1.21.1 modpack with reforged, my game crashes, and I was really looking forward to playing with this mod and including it in a new modpack I'm making! 

<img width="792" alt="Screenshot 2024-10-17 at 4 37 54 PM" src="https://github.com/user-attachments/assets/b6b019e4-0cfc-45ab-869e-4ab91eaa8b82">

**Comment by Stereowalker** [comment]
Oof. I'll update it in a bit. Sorry about that

**Comment by bvbbbles** [comment]
thank you so much! take your time!! super excited to play when the update is released :D

**Comment by Stereowalker** [comment]
It's been done
