### ISSUE TITLE
[BUG] Game crashed on startup when simple clouds is anlong side it

### ISSUE THREAD

**Issue by TimmyWithTheBat21** [Stereowalker/Reforged#117]
well the games crashed on startup when this mod is enabled alongside the simple cloud mod. removes your or the another mod fixes the issue. i dont know why and for me it doesnt make sense but i found it out after taking hours disabling one mod at a time. hope for a fix

**Comment by Stereowalker** [comment]
Hello, update UnionLib to 12.0.9. If it hasn't been fixed for you, please inform me
