### ISSUE TITLE
Crash upon damaging entity

### ISSUE THREAD

**Issue by AzrannAVANA** [Stereowalker/Reforged#118]
I am unsure of what causes this, but I crash everytime I touch any creature. With or without a weapon.
[latest.log](https://github.com/user-attachments/files/18053768/latest.log)

**Comment by Stereowalker** [comment]
Hello, I've just updated the 1.20.1 version of UnionLib and it should fix the issue you're experiencing. If it doesn't, open a new issue and I'll look into it
