### ISSUE TITLE
Blacklisting specific stats (max health) from non-armor items

### ISSUE THREAD

**Issue by Dragnier** [Stereowalker/Reforged#17]
I would like the ability to prevent the max health stat from showing up on any tool, weapon, shield, etc.

Basically, I'm getting tired of burning through my food simply because I have to switch tools a lot. If there is already a way to do this, where is it described? If not, could it be added as a config option of some kind?

(Further note, I'm currently using the latest Forge supported version for 1.16.5 - 2.1.5-forge-beta)

**Comment by LaughingWolf92** [comment]
@Dragnier

> I would like the ability to prevent the max health stat from showing up on any tool, weapon, shield, etc.
> 
> Basically, I'm getting tired of burning through my food simply because I have to switch tools a lot. If there is already a way to do this, where is it described? If not, could it be added as a config option of some kind?
> 
> (Further note, I'm currently using the latest Forge supported version for 1.16.5 - 2.1.5-forge-beta)

I made a custom version of tiered that adds support for bows, crossbows, and removes health attributes from tools. Currently I'm waiting for Stereowalker's approval to upload it, but I can send it privately if you want

**Comment by Stereowalker** [comment]
Dutifully removed
