### ISSUE TITLE
[questions] compat and configs

### ISSUE THREAD

**Issue by Kiryonn** [Stereowalker/Reforged#19]
I wanted to know wether this mod is compatible with tetra (1.18.1).

Also i wanted to know more details about configs. On the main page, it is said how we can use configs for the fabric version. but does forge also uses tags like fabric ? so can we just replace the `fabric` with `forge` and it'll work or is it more complicated that that ?

**Comment by Stereowalker** [comment]
yes, it will work just fine if you replace the fabric tags with forge

**Comment by Stereowalker** [comment]
Also regarding the tetra compatibility, all you need to do is add the respective tags to the tools and armor in the mod and it should work
