### ISSUE TITLE
Mod Support? (Suggestion/Enhancement)

### ISSUE THREAD

**Issue by Coraline77447** [Stereowalker/Reforged#2]
Can you add mod support with Tiered (Forge)? So that items and armors from mods like Tinkers Construct (currently in alpha for 1.16.5 and doesn't have the armors it had in previous versions atm unless the devs of Tinkers Construct have plans to remove it's armors from Tinkers Construct which that'll be unfortunate...) and A.O.A (Advent of Ascension aka Nevermine). Since both fabric version (I don't have fabric and may never use it since forge is way more capable of running more mods at once than fabric btw) and the forge port only does the vanilla armors and items... Unless you allow mod support for modded armors and items to get tiers as well.

**Comment by SHXRKIEgg** [comment]
Adding to this, is it possible to get a config pls? I would something like that armour doesn't give additional health bars. Thanks

**Comment by Stereowalker** [comment]
The reply to this is a year late, but @Coraline77447 You should add tags (forge:sword, forge:chestplate, forge:hoe, and so on) to the armor or tool you want support for. @SharkieTV If you want specific tiers excluded, with the new weight system I implemented you can create custom tiers and set the default Tiers weights to zero to effectively disable them
