### ISSUE TITLE
Creating my own data pack leads to weird naming issue (1.16.5)

### ISSUE THREAD

**Issue by utterlynowhere** [Stereowalker/Reforged#20]
Hi there! I'm creating my own data pack for use and this happens for every new entry I make.

![tiered](https://user-images.githubusercontent.com/37447851/151429274-e80ef816-d426-4b58-8056-cc0c726a3e0a.png)

My code here: 

https://paste.sh/sI-CkFc3#PQgoJAEEqdnnzI9l0VJAEcm-

All I did was copy the values and replace the names from the berserk quality from the mod.

**Comment by Stereowalker** [comment]
You'll need to create a resource pack with a language file with the label of the attribute you added.
You just need to add this line `"tiered.damaged.label" = "Damaged"` to your `en_us.json` language file in the new resource pack you created

**Comment by Stereowalker** [comment]
You'll need to create a resource pack with a language file with the label of the attribute you added.
You just need to add this line '"tiered.damaged.label" = "Damaged"` to your `en_us.json` language file in the new resource pack you created

**Comment by Stereowalker** [comment]
If this solves your problem, close this issue. If not leave a comment with any further problems you might have

**Comment by utterlynowhere** [comment]
Thank you very much! This solved the issue.
