### ISSUE TITLE
Attribute name/stats do not appear after leaving/rejoining a server.

### ISSUE THREAD

**Issue by Sethyboi1** [Stereowalker/Reforged#27]
I have a server featuring Tiered, however if someone times out or quickly leaves to do something, after they rejoin the Tiered attributes no longer display on any item. This causes them to have to either suck it up and continue playing, or needing to restart Minecraft which takes a while since it's modded.

**Comment by Gaxon1** [comment]
I can confirm this happens, however it's only a visual issue. The items still have the tiered attributes, but the rarity and effects aren't displayed on the item.

**Comment by Stereowalker** [comment]
Fixed in 1.18.2
