### ISSUE TITLE
Regarding tags in datapack [1.18.2]

### ISSUE THREAD

**Issue by zalfrost** [Stereowalker/Reforged#29]
Minecraft version: 1.18.2 forge 40.1.0
Mod version: Tiered-1.18.2-4.0.0-Forge.jar
Datapack path: _.minecraft\saves\Faurn\datapacks\zalfrost_epicfight_datapack\data\forge\tags\items_

I've been creating a datapack for some of the mods I use to work with Tiered (Forge) in my world. Upon success in creating the datapack, I found out that some of the tags didn't work. The tags are as follows:-
_-forge:pickaxes
-forge:helmets
-forge:chestplates
-forge:leggings
-forge:boots_

The tags that are working so far are:-
_-forge:swords
-forge:axes
-forge:hoes
-forge:shovels_

Also, I notice that the tags that are on pickaxes are (_forge:tools_ | _forge:tools/pickaxes_). 
This is the same as Armor (helmets, chestplates, leggings, and boots) but It didn't show any tags for Vanilla and Moded armor.

**References 1: the tags that are on pickaxes (Vanilla & Moded are showing the same)**
![Screenshot (805)](https://user-images.githubusercontent.com/90170015/165767405-0b5c10a0-a9d5-4a0d-bbbf-31ca7237aecb.png)

**References 2: one of the tags that are working (Vanilla & Moded are showing the same)**
![Screenshot (806)](https://user-images.githubusercontent.com/90170015/165767684-505d8846-b610-4633-9d8f-4fb3453b55ee.png)

Lastly, I would like to know if I did something wrong and if I did, I would like to know how to fix it. 
Thank you for your time.

**Comment by Stereowalker** [comment]
You don't have the correct pickaxe tag. What you have on your pickaxe currently is `forge:tools/pickaxes` and `forge:tools` not `forge:pickaxes`

**Comment by zalfrost** [comment]
It seems that I type the wrong item id in the JSON file which leads to the mods wiping out the `forge:pickaxes` tag and leaving only the `forge:tools/pickaxes` and `forge:tools` tag. So, I corrected the item id and it seems to be working now. My bad.

Thanks for your time and I'm sorry to take your valuable time for something this silly.

**Comment by Stereowalker** [comment]
No problem. If you have any other issues, just open another issue. I'll try my best to address it
