### ISSUE TITLE
Causes crash, log spam when entering either Blue Skies dimension

### ISSUE THREAD

**Issue by jlaine3333** [Stereowalker/Reforged#32]
Upon entering a Blue Skies dimension, this mod and unionlib both spam the following:
`[03Aug2022 07:05:00.024] [Render thread/INFO] [unionlib/]: unionlib's Clientbound packets registered`
`[03Aug2022 07:05:00.024] [Render thread/INFO] [unionlib/]: tiered's Clientbound packets registered`
constantly. This ultimately crashes the game after some time.

**Comment by Stereowalker** [comment]
My apologies. This will be fixed in a later patch of UnionLib. I'll be closing this issue as I've already resolved it
