### ISSUE TITLE
1.19.2 New Update won't load

### ISSUE THREAD

**Issue by PresBKennedy** [Stereowalker/Reforged#46]
I get the message:
`Mod File Tiered-1.19.2-5.0.4-Forge.jar needs language provider javafml:44 or above to load`

Trying to troubleshoot it, I'm seeing people online saying this error loading message means that I am trying to load a mod for minecraft version 1.19.3 instead of for version 1.19.2.

**Comment by Stereowalker** [comment]
Patched with update, thank you for reporting
