### ISSUE TITLE
[1.19.2] Crash when entering the world

### ISSUE THREAD

**Issue by tangenx** [Stereowalker/Reforged#49]
Mod version - 5.1.0.
Game crashes when using only UnionLib and Tiered, as well as in a large modpack.

[crash-2023-06-06_00.37.31-server.txt](https://github.com/Stereowalker/tiered/files/11657900/crash-2023-06-06_00.37.31-server.txt)

**Comment by Stereowalker** [comment]
Closing this because it's fixed
