### ISSUE TITLE
[1.18.2] Can't find attribute null Crash with specifically 388 or more mods

### ISSUE THREAD

**Issue by Infimyst** [Stereowalker/Reforged#57]
Tiered with 387 mods works perfectly fine on my modpack. Tiered with 388 mods crashes when damaging an entity. Disabling a mod to get back down to 387 mods prevents the crash. 
In the logs below,  I used an insignificant mod on my modpack which is [Chalk](https://www.curseforge.com/minecraft/mc-mods/chalk) - But I have tried dozens of other mods and the issue is consistent: No crashes at 387 or lower, crashes at 388 or more.

[Crash - Tiered with 388 Mods](https://pastebin.com/MjsLphVv)

latest.logs with no crashes below if it helps.
[388 Mods Without Tiered -latest.log](https://github.com/Stereowalker/tiered/files/12423160/388.Mods.Without.Tiered.-latest.log)
[Tiered with 387 Mods - latest.log](https://github.com/Stereowalker/tiered/files/12423162/Tiered.with.387.Mods.-.latest.log)

I also thought it would be a good idea to test this on a server, but upon trying to connect I get this: 
![Screenshot 2023-06-21 181415](https://github.com/Stereowalker/tiered/assets/22278122/0b693dac-8552-4745-8458-4efa3e74aa2f)
[And here is the relevant section of latest.log for that.](https://pastebin.com/dVCHRypj)

**Comment by Stereowalker** [comment]
Please check to see if this have been resolved with UnionLib-7.2.4

**Comment by Infimyst** [comment]
Works perfect, thanks a ton for the update!
