### ISSUE TITLE
Tiered mod with the curios API crash

### ISSUE THREAD

**Issue by Moonseye09** [Stereowalker/Reforged#67]
When the tiered mod is with curios API it starts to crash. Please fix it, Its a pretty cool mod.

**Comment by rai68** [comment]
Can confirm get this error as well here is 2 crash logs

https://pastebin.com/raw/8HybGvNC

Crash
https://pastebin.com/76DrCnfk
Latest
https://pastebin.com/PR2sQABL

**Comment by wickedside** [comment]
Same error

**Comment by Busake** [comment]
same error

**Comment by Looxond** [comment]
same error

**Comment by sunwalkeer** [comment]
Same error

**Comment by scootz** [comment]
Not to sound like a broken record, but I have the same issue here. 
[crash-2024-03-01_17.45.46-fml.txt](https://github.com/Stereowalker/tiered/files/14466719/crash-2024-03-01_17.45.46-fml.txt)

**Comment by Stereowalker** [comment]
@scootz I've resolved the issue with v6.0.4
