### ISSUE TITLE
Swords & Hoes aren't getting tiers

### ISSUE THREAD

**Issue by Subthy** [Stereowalker/Reforged#77]
Mod version: Tiered-1.20.1-6.0.4-Forge

By looking at logs, tags for sword and hoes are broken, thus resulting the swords and hoes not receiving tiers.

Snippet from the log:

`[27May2024 22:53:57.441] [Worker-ResourceReload-2/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [#forge:tools/swords (from Tiered-1.20.1-6.0.4-Forge.jar)] as it is missing following references: #forge:tools/swords (from Tiered-1.20.1-6.0.4-Forge.jar)
[27May2024 22:53:57.441] [Worker-ResourceReload-2/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [#forge:tools/hoes (from Tiered-1.20.1-6.0.4-Forge.jar)] as it is missing following references: #forge:tools/hoes (from Tiered-1.20.1-6.0.4-Forge.jar)`

**Comment by noahtime** [comment]
Same problem just works on Amor and bows ,but no swords pickaxe,axe,shovel or hoe
Pls fix it🙏

**Comment by lazington** [comment]
To anyone still having this problem, the solution is to get Tiered on version 6.0.0, union lib on 10.1. Everything works now, including crafting and stuff.

**Comment by lazington** [comment]
https://github.com/Stereowalker/tiered/assets/91185935/f9a99530-ceff-4c57-9b40-f3cbfa5902f2

Here's proof!

**Comment by Stereowalker** [comment]
Hello, Dev here. I just updated the mod to fix this specific issue

**Comment by Stereowalker** [comment]
Was fixed in 6.0.5 😀
