### ISSUE TITLE
Not an issue! Unofficial QNA! (for the mod) 

### ISSUE THREAD

**Issue by lazington** [Stereowalker/Reforged#78]
Not an all an issue! I just see these frequent issues thrown around and the mod author doesn't seem to answer them at the moment. (This is also for people who dont know how to fiddle with datapacks, I DO NOT CONDONE PPL WHO PUBLICLY SHARE MODIFIED COPIES!!)

FAQ:
How do i make other mods compatible?
-
First, go to data > forge > tags > items
Then, open the json file of the item type you want to make compatible, lets say we want to add a modded chestplate in.
Open 'chestplates.json'
You'd see 
```
{
  "replace": false,
  "values": [
    "minecraft:leather_chestplate",
    "minecraft:chainmail_chestplate",
    "minecraft:iron_chestplate",
    "minecraft:golden_chestplate",
    "minecraft:diamond_chestplate",
    "minecraft:netherite_chestplate"
  ]
}
```
We input the item id of said chestplate in any space so now, it should look something like;
```
{
  "replace": false,
  "values": [
    "minecraft:leather_chestplate",
    "minecraft:chainmail_chestplate",
    "minecraft:iron_chestplate",
    "minecraft:golden_chestplate",
    "minecraft:diamond_chestplate",
    "minecraft:netherite_chestplate",
    "mod:item_chestplate"
  ]
}
```
Don't forget the comma! It will state in your server file that a line of code is unterminated when you try to start it up, and not function. Now head back to data > tiered > pools, and open the folder depending on the type of item. Lets do it with a sword. 
You'd now see something like this:
```
{
  "weight": 3,
  "verifiers": [
    {
      "tag": "minecraft:swords"
    },
    {
      "tag": "minecraft:axes"
    }

  ],
  "tiers": [
    "tiered:melee_weapons/tier",
    "tiered:melee_weapons/tier2"
  ]
}
```
Put in this line of code AFTER axes.
    {
      "tag": "forge:swords"
    }
    So now, the result will be 
```
{
  "weight": 3,
  "verifiers": [
    {
      "tag": "minecraft:swords"
    },
    {
      "tag": "minecraft:axes"
    },
    {
      "tag": "forge:swords"
    }

  ],
  "tiers": [
    "tiered:melee_weapons/relentless",
    "tiered:melee_weapons/lethal"
  ]
}
```
Again, dont forget commas to end a line! 

How do i config items?
- 
(Make sure your server is offline!)
Go to your Tiered mod jar. (Tiered-1.20.1-6.0.x-Forge.Jar)
Right click it, open with winrar.
There will be a json present in the folder lang, en.us
For tiers, go to data > tiered > tiered_modifiers > tiers > (type)
There will be jsons, and you're free to edit it there.

To change names of the tiers,
go to any of the json file, input:
  "literal_name": "(name)",
  In any order as LONG its before "attributes":
  
  So to change a tier, lets say 'Legendary' to 'Insane'
  I'd put it like this:
 ```
 {
  "literal_name": "Insane",
  "weight": 0.5,
  "reforge_experience_cost": 10,
  "reforge_durability_cost": 5,
  "reforge_item": "tiered:weaponsmiths_hammer",
  "style": {
    "color": "gold"
  },
  "attributes": [
```

Rarities dont function, but they do when i loot.
-
Use Tiered 6.0.0
It works for me, somehow
(and use an older version of unionlib compatible with Tiered 6.0.0)
This is fixed in the new version! ^
Thank you so much mod dev!  :D 

Ask any more questions here!

**Comment by Moglibogli** [comment]
Can you explain how to actually do the first part? like where do i get access to that stuff

**Comment by lazington** [comment]
> Can you explain how to actually do the first part? like where do i get access to that stuff

So sorry for such a late reply, but its in the second section; Config items
