### ISSUE TITLE
Issue with tier rolling

### ISSUE THREAD

**Issue by Dogee220** [Stereowalker/Reforged#81]
I use mod "Visual Workbench", that allows you to left items in workbench. So, I can just rolling tier of craftable item by reopening crafting table. Can you please fix that feature? I think that's not fair.

**Comment by Stereowalker** [comment]
From what I can infer, the fact that you can reroll the tier means that the item is getting a tier while in the result slot right?

**Comment by Dogee220** [comment]
Yea, I can get the best tier of item, just by reopening a crafting table. That's make a trouble, because anyone can get the best item tier with out loosing their resources.
I think, that tier must be locked, before item has crafted. Like enchantments in an enchantment table. There player can't get another enchantment just by reopening the table

**Comment by Dogee220** [comment]
Maybe the decision is to hide tier while it's in crafting table and show it when item in user's inventory

**Comment by Stereowalker** [comment]
What's causing this isn't necessarily a bug per se, but the way items are crafted in the Visual Workbench mod. The mod seems to hold not only the ingredients themselves but the result. Fixing the issue would require the Visual Workbench mod to either not store the result of the craft or give you a copy of the result after you craft it to render the tier you saw in the crafting table useless. Any solution I provide for this mod specifically would just break in an update from the mod or minecraft

**Comment by Dogee220** [comment]
https://github.com/Fuzss/visualworkbench

Here is the repository of the mod. Could you check, if the problem there?

**Comment by Dogee220** [comment]
https://github.com/Fuzss/visualworkbench

Here is the repository of the mod. Could you check, if the problem there?

**Comment by Dogee220** [comment]
Yea, you're right, that's it. Visual Workbench makes that issue. I'll just remove it from modpack. But, if you get a decision for that, I'd be very grateful.
