### ISSUE TITLE
What do I use to reforge in Fabric? I have the Weaponsmiths hammer but it doesn't seem to work in the anvil

### ISSUE THREAD

**Issue by Tanjiraaaaa** [Stereowalker/Reforged#82]

**Comment by Tanjiraaaaa** [comment]
![image](https://github.com/Stereowalker/tiered/assets/91242022/d5c914d1-02e1-4ace-ab87-3bf308582478)

**Comment by Stereowalker** [comment]
Thank you for creating this issue. An update to UnionLib will fix this issue and when it's released, I'll close this issue

**Comment by Stereowalker** [comment]
I've fixed the issue in the latest versions of both mods

**Comment by natkos21** [comment]
Same thing happens on forge

EDIT: But only when a weapon "rolls" the extended tier, and *sometimes* when it rolls a berserker and dull tier
