### ISSUE TITLE
The hammer is not being crafted

### ISSUE THREAD

**Issue by Angelessq** [Stereowalker/Reforged#86]
to make a different quality, you need hammers or something like that, but there is no crafting on them, is this a mistake or is this how it should be? 

![2024-07-21_08-10-19](https://github.com/user-attachments/assets/7da68eac-c34c-439b-9dff-8c41eac249b3)

**Comment by Tanjiraaaaa** [comment]
> to make a different quality, you need hammers or something like that, but there is no crafting on them, is this a mistake or is this how it should be?
> 
> ![2024-07-21_08-10-19](https://private-user-images.githubusercontent.com/175457033/350738598-7da68eac-c34c-439b-9dff-8c41eac249b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NDg5OTcsIm5iZiI6MTcyMTU0ODY5NywicGF0aCI6Ii8xNzU0NTcwMzMvMzUwNzM4NTk4LTdkYTY4ZWFjLWMzNGMtNDM5Yi05ZGZmLThjNDFlYWMyNDliMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQwNzU4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmE2OWQ5YTI4MWU1MWEyNTJmMWJkOWRiYjU2YTEwZjhlNzQwMThjZWNhOTY1YWM3ZmIzOTRhOGJmY2MyYzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tJEBJD3vLU889YEowb-q5aDONZeZ_fU1uI4jkCIgjSc)

You need to trade with it's respective villagers

**Comment by Angelessq** [comment]
im try
