### ISSUE TITLE
After adding Reforged, every weapon deals only 2.5 hearts of damage.

### ISSUE THREAD

**Issue by Tanjiraaaaa** [Stereowalker/Reforged#88]
It doesn't matter what the enchants, attributes, ... are
Every weapon deals only 2.5 hearts of damage

**Comment by Tanjiraaaaa** [comment]
This is happening on the 1.20.6 version of Minecraft
And 1.0.1 version of Reforged

**Comment by MTSKING** [comment]
same error

**Comment by MTSKING** [comment]
@Stereowalker pls reply

**Comment by Stereowalker** [comment]
Thank you for reporting thie issue, this will be fixed with an update to UnionLib on Fabric

**Comment by Stereowalker** [comment]
Fixed with UnionLib 12.0.4.
